image: docker:stable
services:
  - docker:dind
stages:
  - build
build_image:
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    DOCKER_HOST: tcp://docker:2375
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --build-arg HOST_USER_ID=1001 --pull -t $IMAGE_TAG -f Dockerfile .
    - docker push $IMAGE_TAG
  only:
    - master
