#image: docker:stable
#
#services:
#  - docker:dind
#stages:
#  - build
#
#before_script:
#  - docker info
#  - apk update
#  - apk upgrade
#  - apk add --no-cache docker-compose
#  - docker-compose up -d
#
#build-prod:
#  stage: build
#  script:
#    - docker-compose build
#  #build_image:
#  #  stage: build
#  #  variables:
#  #    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
#  #    DOCKER_HOST: tcp://docker:2375
#  #  script:
#  #    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
#  #    - docker build --build-arg HOST_USER_ID=1001 --pull -t $IMAGE_TAG -f Dockerfile .
#  #    - docker push $IMAGE_TAG
#  only:
#    - master

# .gitlab-ci.yml
image: docker

services:
  - docker:dind

stages:
  - build
  - testing
  - deploy

build-project:
  stage: build
  before_script:
    - cp .env.example .env
  script:
    - apk add --no-cache docker-compose
    - docker-compose up -d
    - docker run --rm -v $(pwd):/app composer install
    - HOST_USER_ID=$(grep HOST_USER_ID .env | xargs) && HOST_USER_ID=${HOST_USER_ID#*=}
    - cd .. && chmod -R 777 tesis-ing-software && cd tesis-ing-software
    - docker-compose exec -T app php artisan key:generate
    - docker-compose exec -T db mysql -u root -p'4YUNT4M13NT0.Z4C4T3C45' -e "GRANT ALL ON sigaz.* TO 'sigaz'@'%' IDENTIFIED BY 'sigaz_4YUNT4M13NT0';FLUSH PRIVILEGES;"
    - docker-compose exec -T app php artisan migrate:fresh --seed

unit-testing:
  stage: testing
  script:
    - echo "Aquí se ejecutarán las pruebas unitarias"

feature-testing:
  stage: testing
  script:
    - echo "Aquí se ejecutarán las feature testing"

#prepare-laravel:
#  stage: build
#  script:
#    -
#    -
